baseURL = 'https://www.stefansommarsjo.com/'
languageCode = 'en-us'
title = 'Stefan Sommarsjö'
theme = 'PaperMod'
[params]
  env = 'production'
  subtitle = "Creating Stuff..."
  description = 'Creating Stuff...'
  keywords = ["sommarsjö", "sommarsjo", "creating", "ludvika"]
  dateFormat = "January 2, 2006"
  ShowShareButtons = true
  assets.favicon = 'favicon.ico'
  favicon = 'static/favicon.ico'
