baseURL = 'https://www.stefansommarsjo.com/'
languageCode = 'en-us'
title = 'Stefan Sommarsjö'
theme = 'PaperMod'
[params]
  ShowHome = true
  env = 'production'
  subtitle = "Creating Stuff..."
  description = 'Creating Stuff...'
  keywords = ["sommarsjö", "sommarsjo", "creating", "ludvika"]
  dateFormat = "January 2, 2006"
  ShowShareButtons = true
  ShowPostNavLinks = true
  defaultTheme = "dark"
  assets.favicon = "https://www.stefansommarsjo.com/favicon.ico"
  favicon = "https://www.stefansommarsjo.com/favicon.ico"
  ShowReadingTime = true
  showtoc = true


  [params.profileMode]
  enabled = false
  title = "Stefan Sommarsjö"
  subtitle = "Breaking free from subscriptions"


[[params.socialIcons]]
  name = "github"
  url = "https://github.com/sestsom"


